//! The copy-and-patch baseline JIT.
//!
//! There is no assembler here. All the machine code was emitted by clang at
//! build time (see `csrc/stencils.c` and `build.rs`); compiling a function is
//! just:
//!
//! 1. concatenate one pre-compiled stencil per bytecode op into an mmap'd
//!    buffer, then
//! 2. fill in the holes clang left behind -- the `jmp`/`jcc` displacements
//!    that thread one op to the next, and the 32-bit immediates that carry
//!    operands.
//!
//! Since each stencil ends in a `musttail` call, the whole function body is
//! one long chain of `jmp`s: no dispatch loop, no bytecode fetch, and the
//! native stack only grows on real calls.

use std::fmt::Write as _;
use std::ptr;

use crate::bytecode::{Function, Op};

/// Tables generated by `build.rs` from clang's output.
pub mod stencils {
    include!(concat!(env!("OUT_DIR"), "/stencils.rs"));
}

use stencils::{HoleKind, STENCILS};

#[derive(Debug)]
pub enum JitError {
    /// The bytecode violated an invariant the stencil layout depends on.
    Unsupported(String),
    /// `mmap`/`mprotect` failed.
    Mmap(std::io::Error),
}

impl std::fmt::Display for JitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            JitError::Unsupported(m) => write!(f, "cannot JIT this function: {m}"),
            JitError::Mmap(e) => write!(f, "could not allocate executable memory: {e}"),
        }
    }
}

/// An executable buffer holding one compiled function.
pub struct JitCode {
    ptr: *mut u8,
    /// Bytes of code actually emitted.
    len: usize,
    /// Bytes handed out by `mmap` (page-rounded).
    mapped: usize,
    /// Byte offset of each bytecode op's code, plus a trailing sentinel.
    offsets: Vec<u32>,
}

impl JitCode {
    /// Address of the first op's code: the function's entry point.
    pub fn entry(&self) -> *const u8 {
        self.ptr
    }

    pub fn len(&self) -> usize {
        self.len
    }

    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Human-readable listing: which stencil landed where, and its bytes.
    pub fn dump(&self, f: &Function) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "jit fn {}  {} bytes at {:p}", f.name, self.len, self.ptr);
        for (i, op) in f.code.iter().enumerate() {
            let start = self.offsets[i] as usize;
            let end = self.offsets[i + 1] as usize;
            // SAFETY: the range is inside the buffer we allocated, and the
            // pages are still mapped for as long as `self` lives.
            let bytes = unsafe { std::slice::from_raw_parts(self.ptr.add(start), end - start) };
            let hex: Vec<String> = bytes.iter().map(|b| format!("{b:02x}")).collect();
            let _ = writeln!(
                s,
                "  +{start:<5} {i:>4}  {:<14} {}",
                op.mnemonic(),
                hex.join(" ")
            );
        }
        s
    }
}

impl Drop for JitCode {
    fn drop(&mut self) {
        // SAFETY: `ptr`/`mapped` come from the successful `mmap` in `compile`
        // and are unmapped exactly once.
        unsafe {
            libc::munmap(self.ptr as *mut libc::c_void, self.mapped);
        }
    }
}

/// Compiles `f` into a chain of patched stencils.
pub fn compile(f: &Function) -> Result<JitCode, JitError> {
    if f.code.is_empty() {
        return Err(JitError::Unsupported("empty function body".into()));
    }
    // Every stencil except `ret` ends in a jump to the *next* op, so the last
    // op must be the one that has no successor.
    if f.code.last() != Some(&Op::Return) {
        return Err(JitError::Unsupported(
            "function does not end in `return`".into(),
        ));
    }

    let ids: Vec<usize> = f.code.iter().map(|op| stencil_for(*op)).collect();

    let mut offsets = Vec::with_capacity(ids.len() + 1);
    let mut total = 0usize;
    for &id in &ids {
        offsets.push(total as u32);
        total += STENCILS[id].emitted_len();
    }
    offsets.push(total as u32);

    let mapped = total.next_multiple_of(page_size());
    // SAFETY: a fresh anonymous mapping; the arguments are the standard ones
    // and the result is checked below.
    let raw = unsafe {
        libc::mmap(
            ptr::null_mut(),
            mapped,
            libc::PROT_READ | libc::PROT_WRITE,
            libc::MAP_PRIVATE | libc::MAP_ANONYMOUS,
            -1,
            0,
        )
    };
    if raw == libc::MAP_FAILED {
        return Err(JitError::Mmap(std::io::Error::last_os_error()));
    }
    let code = JitCode {
        ptr: raw as *mut u8,
        len: total,
        mapped,
        offsets,
    };

    // Lay the stencils down back to back...
    for (i, &id) in ids.iter().enumerate() {
        let st = &STENCILS[id];
        // SAFETY: `offsets[i] + emitted_len() <= total <= mapped`, and the
        // mapping is writable until the `mprotect` at the end of this function.
        unsafe {
            ptr::copy_nonoverlapping(
                st.code.as_ptr(),
                code.ptr.add(code.offsets[i] as usize),
                st.emitted_len(),
            );
        }
    }

    // ...then fill in the holes, now that every op's address is known.
    let base = code.ptr as i64;
    for (i, &id) in ids.iter().enumerate() {
        let st = &STENCILS[id];
        let op = f.code[i];
        let (imm_a, imm_b) = operands(op);
        let stencil_at = code.offsets[i] as usize;

        for hole in st.holes {
            // The trailing `jmp` to the next op, if there was one, was not
            // copied; falling through gets to the same place.
            if hole.offset as usize + 4 > st.emitted_len() {
                continue;
            }
            let site = stencil_at + hole.offset as usize;
            let value: i64 = match hole.kind {
                HoleKind::Next => base + code.offsets[i + 1] as i64,
                HoleKind::Target => {
                    let t = op.target().ok_or_else(|| {
                        JitError::Unsupported(format!(
                            "stencil `{}` wants a branch target but `{}` has none",
                            st.name,
                            op.mnemonic()
                        ))
                    })?;
                    base + code.offsets[t] as i64
                }
                HoleKind::ImmA => imm_a as i64,
                HoleKind::ImmB => imm_b as i64,
                HoleKind::ImmPc => i as i64,
            };

            let word = if hole.pcrel {
                // S + A - P, the usual x86-64 PC-relative relocation.
                let rel = value + hole.addend - (base + site as i64);
                i32::try_from(rel)
                    .map_err(|_| {
                        JitError::Unsupported(format!(
                            "jump displacement {rel} does not fit in 32 bits"
                        ))
                    })?
                    .to_le_bytes()
            } else {
                let abs = value + hole.addend;
                u32::try_from(abs)
                    .map_err(|_| {
                        JitError::Unsupported(format!("immediate {abs} does not fit in 32 bits"))
                    })?
                    .to_le_bytes()
            };

            // SAFETY: build.rs checked that every hole's 4 bytes lie inside its
            // stencil, so `site + 4 <= total <= mapped`.
            unsafe {
                ptr::copy_nonoverlapping(word.as_ptr(), code.ptr.add(site), 4);
            }
        }
    }

    // SAFETY: same mapping, now finished being written.
    let rc = unsafe {
        libc::mprotect(
            code.ptr as *mut libc::c_void,
            code.mapped,
            libc::PROT_READ | libc::PROT_EXEC,
        )
    };
    if rc != 0 {
        return Err(JitError::Mmap(std::io::Error::last_os_error()));
    }

    Ok(code)
}

fn page_size() -> usize {
    // SAFETY: `sysconf` is always safe to call with a valid name.
    let n = unsafe { libc::sysconf(libc::_SC_PAGESIZE) };
    if n > 0 {
        n as usize
    } else {
        4096
    }
}

fn stencil_for(op: Op) -> usize {
    use stencils::id;
    match op {
        Op::Const(_) => id::PUSH_CONST,
        Op::LoadLocal(_) => id::LOAD_LOCAL,
        Op::StoreLocal(_) => id::STORE_LOCAL,
        Op::Pop => id::POP,
        Op::Add => id::ADD,
        Op::Sub => id::SUB,
        Op::Mul => id::MUL,
        Op::Div => id::DIV,
        Op::Rem => id::REM,
        Op::Neg => id::NEG,
        Op::Not => id::NOT,
        Op::Lt => id::LT,
        Op::Le => id::LE,
        Op::Gt => id::GT,
        Op::Ge => id::GE,
        Op::Eq => id::EQ,
        Op::Ne => id::NE,
        Op::Jump(_) => id::JUMP,
        Op::JumpIfFalse(_) => id::JUMP_IF_FALSE,
        Op::Call { .. } => id::CALL,
        Op::CallValue { .. } => id::CALL_VALUE,
        Op::Return => id::RET,
        Op::Print => id::PRINT,
    }
}

/// The two 32-bit immediates a stencil may ask for.
fn operands(op: Op) -> (u32, u32) {
    match op {
        Op::Const(k) | Op::LoadLocal(k) | Op::StoreLocal(k) => (k, 0),
        Op::Call { func, argc } => (func, argc),
        Op::CallValue { argc } => (0, argc),
        _ => (0, 0),
    }
}

/// Listing of the stencil table itself, for `--dump-stencils`.
pub fn dump_stencils() -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "{} stencils, {} bytes of clang-generated code embedded in the source",
        STENCILS.len(),
        stencils::CODE_SIZE
    );
    for st in STENCILS {
        let hex: Vec<String> = st.code.iter().map(|b| format!("{b:02x}")).collect();
        let _ = writeln!(
            s,
            "  {:<16} {:>3} bytes{}",
            st.name,
            st.code.len(),
            if st.tail_jump {
                format!(" ({} emitted; trailing jmp elided)", st.emitted_len())
            } else {
                String::new()
            }
        );
        let _ = writeln!(s, "    {}", hex.join(" "));
        for h in st.holes {
            let _ = writeln!(
                s,
                "    hole +{:<3} {:?}{} addend {}",
                h.offset,
                h.kind,
                if h.pcrel {
                    " (pc-relative)"
                } else {
                    " (absolute)"
                },
                h.addend
            );
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_op_has_a_stencil() {
        // A stencil that ends the chain must have no `Next` hole, and every
        // other stencil must have exactly one way to continue.
        for st in STENCILS {
            let nexts = st.holes.iter().filter(|h| h.kind == HoleKind::Next).count();
            let targets = st
                .holes
                .iter()
                .filter(|h| h.kind == HoleKind::Target)
                .count();
            match st.name {
                "ret" => assert_eq!(nexts + targets, 0, "`ret` should not continue"),
                "jump" => assert_eq!(
                    (nexts, targets),
                    (0, 1),
                    "`jump` is an unconditional branch"
                ),
                "jump_if_false" => assert_eq!((nexts, targets), (1, 1)),
                other => assert_eq!(
                    nexts, 1,
                    "stencil `{other}` must fall through to the next op"
                ),
            }
        }
    }

    #[test]
    fn a_trailing_jump_to_the_next_op_is_elided() {
        // These are the stencils clang compiles down to straight-line code
        // ending in the chain jump; dropping it is pure profit.
        let trimmed: Vec<&str> = STENCILS
            .iter()
            .filter(|st| st.tail_jump)
            .map(|st| st.name)
            .collect();
        assert!(
            trimmed.contains(&"push_const") && trimmed.contains(&"load_local"),
            "expected the simple stencils to end in a chain jump, got {trimmed:?}"
        );
        for st in STENCILS {
            if st.tail_jump {
                assert_eq!(st.code[st.code.len() - 5], 0xE9, "`{}`", st.name);
                assert_eq!(st.emitted_len(), st.code.len() - 5);
            }
        }
        // `ret` ends the chain, so there is nothing to elide.
        assert!(!STENCILS.iter().any(|st| st.name == "ret" && st.tail_jump));
    }

    #[test]
    fn holes_stay_inside_their_stencil() {
        for st in STENCILS {
            for h in st.holes {
                assert!(
                    h.offset as usize + 4 <= st.code.len(),
                    "hole at +{} runs past the end of `{}` ({} bytes)",
                    h.offset,
                    st.name,
                    st.code.len()
                );
            }
        }
    }
}
